using System.Collections;
using System.Collections.Immutable;
using System.Reflection;
using System.Runtime.CompilerServices;
using Xunit;

namespace FaaPart107.Tests;

/// <summary>
/// The corpus declares <c>randomness: none</c> (rules-factory decision 0019). The gate refuses the
/// randomness package at restore; these check the built engine too.
/// </summary>
/// <remarks>
/// The last two measure a census of the built assembly rather than restating one, on the model of
/// <c>OperationEvaluatorTests.The_cost_recorded_in_decision_0004_is_the_cost_the_engine_actually_has</c>.
/// Issue #97's own criterion asked it to <em>check</em> that every finding compares by value rather
/// than assume it, and the answer was written three times as pasted output nothing in this
/// repository emitted — and was wrong twice. A claim that has been wrong twice belongs where a check
/// looks.
/// <para>
/// Like everything in this file they belong to no map entry, so the overlay cannot name them and
/// cannot hold the mutation that makes each fail. That gap is <c>#98</c> and not theirs to close;
/// the mutations were observed and are recorded in <c>#97</c>'s pull request instead —
/// <c>OperatingLimitationsFinding</c>'s equality override removed for the first, and a sixth
/// <c>MapEntry</c>-valued field added to <c>LimitationOutcome</c> for the second, each turning
/// its test red by naming the record that joined the census.
/// </para>
/// </remarks>
public class DeterminismTests
{
    /// <summary>
    /// The records whose equality is the compiler's <em>and</em> which hold a collection field that
    /// compares by the identity of the object behind it. Every one is a defect of the same shape
    /// (<c>AGENTS.md</c> §8), and every one is already owned by an issue; what this list is for is
    /// that a new one of the kinds <see cref="ComparesByIdentity"/> recognises does not appear
    /// unremarked.
    /// </summary>
    /// <remarks>
    /// In name order, so that a record joining it lands where a reader would look for it.
    /// <c>DerivedMapEntry</c>, <c>MapEntry</c> and <c>RegisteredEntry</c> are generated by
    /// rules-factory and so not this engine's to fix: <c>#110</c>, upstream
    /// <c>rules-factory#462</c>. <c>OperationFacts</c> is the evaluator's input rather than any
    /// answer of this engine's, and is never reachable through
    /// <c>EvaluatedRequirement.Finding</c>: <c>#109</c>.
    /// </remarks>
    private static readonly string[] KnownToCompareACollectionByIdentity =
    [
        "DerivedMapEntry",
        "MapEntry",
        "OperationFacts",
        "RegisteredEntry",
    ];

    /// <summary>
    /// Every record field in the assembly whose value is one of the map's own entry types, counted
    /// through element types as well as directly. They are what makes
    /// <see cref="Evaluation.EvaluatedRequirement.Equals(Evaluation.EvaluatedRequirement)"/>'s
    /// comparison of a finding reduce to <c>MapEntry</c>'s generated equality, and the condition
    /// that keeps that sound is on the type; the list is here so that a new one has to be
    /// considered against that condition rather than discovered later.
    /// </summary>
    private static readonly string[] KnownToCarryAMapEntry =
    [
        "Assertion.Entry",
        "ExceptedCaseOutcome.Entry",
        "LimitationOutcome.Entry",
        "ObligationOutcome.Entry",
        "RequirementOutcome.Answering",
    ];

    /// <summary>
    /// Every record type in the built engine — <c>record</c> and <c>record struct</c> alike — in a
    /// fixed order.
    /// </summary>
    /// <remarks>
    /// The filter is the synthesized <c>PrintMembers</c>, which every record has.
    /// <c>&lt;Clone&gt;$</c> looks like the obvious one and is not: the compiler emits it only for
    /// a record <em>class</em>, because <c>with</c> on a value type is a direct copy. Filtering on
    /// it left this engine's two record structs — <see cref="Groundspeed"/> and
    /// <see cref="TwilightBoundary"/> — outside a census whose prose said it ranged over every
    /// record. Neither carries a collection or a map entry, so nothing the censuses assert was
    /// wrong; what was wrong was the claim, and a finding declared <c>readonly record struct</c>
    /// over an <see cref="ImmutableArray{T}"/> would have been invisible to both while being
    /// exactly the defect they exist to catch.
    /// </remarks>
    private static IEnumerable<Type> Records() =>
        typeof(EntryPoints).Assembly.GetTypes()
            .Where(type => type.GetMethod("PrintMembers", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic) is not null)
            .OrderBy(type => type.FullName, StringComparer.Ordinal);

    /// <summary>
    /// A record's synthesized <c>Equals</c> compares its <em>fields</em>, never a computed
    /// property, so the census is over fields — the backing field of an <c>init</c> property
    /// included.
    /// </summary>
    /// <remarks>
    /// <c>DeclaredOnly</c>, so a record inheriting a field from a base record would have that
    /// field counted against the base and not against it. No record here has a base record — the
    /// only one with a base list at all is <see cref="SufficientAvailablePowerFinding"/>, whose
    /// base is an interface — so nothing is missed today; a record hierarchy would need this
    /// reconsidered.
    /// </remarks>
    private static IEnumerable<FieldInfo> Fields(Type type) =>
        type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly);

    /// <summary>
    /// Whether a value of this type is compared by the identity of an object behind it rather than
    /// by what it holds.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Three cases, and only one of them is decided by naming a type. An <b>array</b> is compared
    /// by reference. A collection seen through an <b>interface</b> could be anything at run time,
    /// so nothing can be assumed about its equality. And a <b>concrete</b> collection class is
    /// compared by reference exactly when it leaves <see cref="object.Equals(object)"/> where it
    /// found it — asked of the type rather than written down, so
    /// <c>ImmutableDictionary&lt;,&gt;</c>, <c>List&lt;T&gt;</c> and anything else of that kind is
    /// caught without being named. <c>OperationFacts.Waivers</c> is the live example here.
    /// </para>
    /// <para>
    /// <see cref="ImmutableArray{T}"/> is named, and it is the one case that has to be. It is a
    /// value type that <em>does</em> override equality, so the reference-equality question answers
    /// "no" for it — but what its equality compares is the array behind it, which is the same
    /// defect. A general test for "equality that does not reach the elements" would have to build
    /// two equal-content instances and compare them; that is more machinery than this census is
    /// worth, so the exception is written down where it can be read instead.
    /// </para>
    /// <para>
    /// <b>The limit that follows from that</b>, and it is the same shape as the named exception:
    /// another struct collection that overrides <c>Equals(object)</c> while comparing something
    /// held by reference would answer "no" here and be missed — <c>ArraySegment&lt;T&gt;</c> is
    /// the standard example. None is in play in this assembly; if one arrives, it joins
    /// <see cref="ImmutableArray{T}"/> above rather than being caught by the rule.
    /// </para>
    /// </remarks>
    private static bool ComparesByIdentity(Type type) =>
        type != typeof(string)
        && (type.IsArray
            || (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(ImmutableArray<>))
            || (typeof(IEnumerable).IsAssignableFrom(type)
                && (type.IsInterface || UsesReferenceEquality(type))));

    /// <summary>
    /// Whether this type leaves <see cref="object.Equals(object)"/> where it found it, which is
    /// reference equality.
    /// </summary>
    private static bool UsesReferenceEquality(Type type) =>
        type.GetMethod("Equals", BindingFlags.Instance | BindingFlags.Public, null, [typeof(object)], null)
            ?.DeclaringType == typeof(object);

    /// <summary>Whether this type keeps the equality the compiler wrote for it.</summary>
    private static bool KeepsSynthesizedEquality(Type type) =>
        type.GetMethod("Equals", BindingFlags.Instance | BindingFlags.Public, null, [type], null)
            is not { } equals || equals.IsDefined(typeof(CompilerGeneratedAttribute), inherit: false);

    /// <summary>
    /// Every type a value of <paramref name="type"/> carries: itself, an array's element type, and
    /// every generic type argument — so <c>IReadOnlyList&lt;LimitationOutcome&gt;</c> yields
    /// <c>LimitationOutcome</c>. Walking field types alone reaches none of those, which is how a
    /// census of this missed four of its five answers (#97).
    /// </summary>
    private static IEnumerable<Type> Carried(Type type)
    {
        var bare = Nullable.GetUnderlyingType(type) ?? type;
        yield return bare;

        var inner = bare.IsArray && bare.GetElementType() is { } element
            ? [element]
            : bare.IsGenericType ? bare.GetGenericArguments() : [];
        foreach (var carried in inner.SelectMany(Carried))
        {
            yield return carried;
        }
    }

    [Fact]
    public void The_engine_assembly_references_the_kernel_and_never_the_randomness_package()
    {
        var referenced = typeof(EntryPoints).Assembly.GetReferencedAssemblies()
            .Select(a => a.Name ?? string.Empty)
            .Where(n => n.StartsWith("RulesKernel", StringComparison.Ordinal))
            .ToArray();

        Assert.Contains("RulesKernel", referenced);
        Assert.DoesNotContain("RulesKernel.Randomness", referenced);
    }

    [Fact]
    public void The_replay_identity_names_no_random_algorithm_and_pins_the_corpus()
    {
        Assert.True(Ruleset.Identity.IsDeterministicWithoutRandomness);
        Assert.Null(Ruleset.Identity.RandomAlgorithm);
        Assert.Equal(MapEntries.Baseline, Assert.Single(Ruleset.Identity.SourceBaselines));
    }

    [Fact]
    public void The_same_request_resolves_the_same_way_every_time()
    {
        var waiver = WaiverStatement.NoneHeld("§ 107.51", nameof(DeterminismTests));
        var request = new Requests.SpeedWithinLimitRequest { Groundspeed = Groundspeed.InMilesPerHour(99m), Waiver = waiver };

        var first = EntryPoints.SpeedWithinLimit.Resolve(request);
        for (var i = 0; i < 100; i++)
        {
            Assert.Equal(first, EntryPoints.SpeedWithinLimit.Resolve(request));
        }
    }

    /// <summary>
    /// No record in this engine both carries a collection compared by the identity of the object
    /// behind it and keeps the equality the compiler wrote — save four this repository has already
    /// taken up, none of which is a finding.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is what carries most of the weight in
    /// <see cref="Evaluation.EvaluatedRequirement.Equals(Evaluation.EvaluatedRequirement)"/>'s
    /// comparison of a finding, and unlike the three audits that preceded it, it asks nothing
    /// about which findings are reachable: it ranges over every record type the assembly holds, so
    /// a finding no fact set this repository knows how to build could ever produce is inside it
    /// anyway.
    /// </para>
    /// <para>
    /// <b>What it does not establish</b>, stated because five rounds of this issue were lost to
    /// claims wider than their method — the fifth to the sentence that used to stand here, which
    /// reassured about records where it should have warned that <see cref="Records"/> then saw
    /// only record <em>classes</em>. Four limits, each of which would let a real defect through:
    /// </para>
    /// <para>
    /// (a) It covers <em>records</em>, so it covers findings only while every finding is a record.
    /// True of this assembly today; prose here rather than a check.
    /// (b) It says a record overrides its equality, never that the override compares its
    /// collection by element — that is what the <b>four</b> <c>..._compared_by_element</c> tests
    /// are for, under <c>operating-limitations</c>, <c>over-human-beings</c>,
    /// <c>visual-observer-conditions</c> and <c>preflight-actions</c>, and this census would stay
    /// green if one of them were gutted. The fifth record named in the guard below,
    /// <see cref="MultipleAircraftFinding"/>, has no such test of its own: what backstops it is
    /// <c>OperationEvaluatorTests.The_same_facts_evaluate_the_same_way_every_time</c>, which now
    /// reaches it — <see cref="MultipleAircraft"/> builds the finding's engagements fresh on every
    /// resolve, so two evaluations of one operation carry two lists, and since <c>#97</c> that
    /// comparison runs through <see cref="Evaluation.EvaluatedRequirement.Finding"/> rather than
    /// past it.
    /// (c) It sees only the kinds of field <see cref="ComparesByIdentity"/> recognises, whose own
    /// limits are written there.
    /// (d) It reads instance fields declared on the type (<see cref="Fields"/>), so a static
    /// holding a collection — <c>MapEntries</c>' entries, <c>Registry</c>'s
    /// <c>ImmutableArray&lt;RegisteredEntry&gt;</c> — is not in view. Nothing compares two of
    /// those, so no outcome turns on them; they are simply not what this counts.
    /// </para>
    /// <para>
    /// It fails by <em>name</em>, so a record that joins the list says which record and the reader
    /// does not have to rediscover it. Adding a name here is a decision, not a fix: it means the
    /// engine has one more place where two evaluations of one operation can differ over which
    /// object happened to carry an answer.
    /// </para>
    /// </remarks>
    [Fact]
    public void No_record_compares_a_collection_by_its_identity_but_the_four_already_taken_up()
    {
        var carryingOne = Records()
            .Where(type => Fields(type).Any(field => ComparesByIdentity(field.FieldType)))
            .ToArray();

        // The census is only worth anything if it is looking at something, so these five must be
        // among what it examined: the four findings #90 gave their own equality, and
        // MultipleAircraftFinding, which is the precedent those four cite rather than one of them.
        Assert.Contains(typeof(OperatingLimitationsFinding), carryingOne);
        Assert.Contains(typeof(OverHumanBeingsFinding), carryingOne);
        Assert.Contains(typeof(PreflightActionsFinding), carryingOne);
        Assert.Contains(typeof(VisualObserverConditionsFinding), carryingOne);
        Assert.Contains(typeof(MultipleAircraftFinding), carryingOne);

        Assert.Equal(
            KnownToCompareACollectionByIdentity,
            carryingOne.Where(KeepsSynthesizedEquality).Select(type => type.Name).Order(StringComparer.Ordinal).ToArray());
    }

    /// <summary>
    /// Every <em>record instance field</em> in this engine whose value is one of the map's own
    /// entry types, counted through element types as well as directly, is one of five this
    /// repository has looked at.
    /// </summary>
    /// <remarks>
    /// Comparing a finding reduces, level by level, to these — and <c>MapEntry</c> keeps the
    /// compiler's equality over an <see cref="ImmutableArray{T}"/>, so what keeps that sound is a
    /// condition stated on
    /// <see cref="Evaluation.EvaluatedRequirement.Equals(Evaluation.EvaluatedRequirement)"/> rather
    /// than anything here. This is the census that condition has to be true of, and it is measured
    /// rather than written down: a field that joins it turns this red by name, where prose about it
    /// went stale twice inside one change.
    /// <para>
    /// Record instance fields and no others, which is the right scope and not the whole assembly:
    /// what the condition is about is a map entry reached while comparing two values, and only a
    /// field of a record is reached that way. A static holding entries — <c>MapEntries</c>',
    /// <c>Registry</c>'s <c>ImmutableArray&lt;RegisteredEntry&gt;</c> — is never one side of a
    /// comparison, and is not counted here.
    /// </para>
    /// </remarks>
    [Fact]
    public void Every_record_field_carrying_a_map_entry_is_one_of_the_five_the_soundness_condition_covers()
    {
        var mapSide = Records()
            .SelectMany(type => Fields(type).Select(field => (Type: type, Field: field)))
            .Where(held => Carried(held.Field.FieldType).Any(
                carried => carried == typeof(MapEntry) || carried == typeof(DerivedMapEntry) || carried == typeof(RegisteredEntry)))

            // The backing field of `Entry` is named `<Entry>k__BackingField`; the property is what
            // a reader recognises.
            .Select(held => $"{held.Type.Name}.{held.Field.Name.TrimStart('<').Split('>')[0]}")
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();

        Assert.Equal(KnownToCarryAMapEntry, mapSide);
    }
}
