using System.Collections;
using System.Collections.Immutable;
using System.Reflection;
using System.Runtime.CompilerServices;
using Xunit;

namespace FaaPart107.Tests;

/// <summary>
/// The corpus declares <c>randomness: none</c> (rules-factory decision 0019). The gate refuses the
/// randomness package at restore; these check the built engine too.
/// </summary>
/// <remarks>
/// The last two measure a census of the built assembly rather than restating one, on the model of
/// <c>OperationEvaluatorTests.The_cost_recorded_in_decision_0004_is_the_cost_the_engine_actually_has</c>.
/// Issue #97's own criterion asked it to <em>check</em> that every finding compares by value rather
/// than assume it, and the answer was written three times as pasted output nothing in this
/// repository emitted — and was wrong twice. A claim that has been wrong twice belongs where a check
/// looks.
/// <para>
/// Like everything in this file they belong to no map entry, so the overlay cannot name them and
/// cannot hold the mutation that makes each fail. That gap is <c>#98</c> and not theirs to close;
/// the mutations were observed and are recorded in <c>#97</c>'s pull request instead —
/// <c>OperatingLimitationsFinding</c>'s equality override removed for the first, and a sixth
/// <c>MapEntry</c>-valued field added to <c>LimitationOutcome</c> for the second, each turning
/// its test red by naming the record that joined the census.
/// </para>
/// </remarks>
public class DeterminismTests
{
    /// <summary>
    /// The records whose equality is the compiler's <em>and</em> which hold a collection field that
    /// compares by the identity of the object behind it. Every one is a defect of the same shape
    /// (<c>AGENTS.md</c> §8), and every one is already owned by an issue; what this list is for is
    /// that a <em>new</em> one cannot appear unremarked.
    /// </summary>
    /// <remarks>
    /// In name order, so that a record joining it lands where a reader would look for it.
    /// <c>DerivedMapEntry</c>, <c>MapEntry</c> and <c>RegisteredEntry</c> are generated by
    /// rules-factory and so not this engine's to fix: <c>#110</c>, upstream
    /// <c>rules-factory#462</c>. <c>OperationFacts</c> is the evaluator's input rather than any
    /// answer of this engine's, and is never reachable through
    /// <c>EvaluatedRequirement.Finding</c>: <c>#109</c>.
    /// </remarks>
    private static readonly string[] KnownToCompareACollectionByIdentity =
    [
        "DerivedMapEntry",
        "MapEntry",
        "OperationFacts",
        "RegisteredEntry",
    ];

    /// <summary>
    /// Every record field in the assembly whose value is one of the map's own entry types, counted
    /// through element types as well as directly. They are what makes
    /// <see cref="Evaluation.EvaluatedRequirement.Equals(Evaluation.EvaluatedRequirement)"/>'s
    /// comparison of a finding reduce to <c>MapEntry</c>'s generated equality, and the condition
    /// that keeps that sound is on the type; the list is here so that a new one has to be
    /// considered against that condition rather than discovered later.
    /// </summary>
    private static readonly string[] KnownToCarryAMapEntry =
    [
        "Assertion.Entry",
        "ExceptedCaseOutcome.Entry",
        "LimitationOutcome.Entry",
        "ObligationOutcome.Entry",
        "RequirementOutcome.Answering",
    ];

    /// <summary>Every record type in the built engine, in a fixed order.</summary>
    private static IEnumerable<Type> Records() =>
        typeof(EntryPoints).Assembly.GetTypes()
            .Where(type => type.GetMethod("<Clone>$", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic) is not null)
            .OrderBy(type => type.FullName, StringComparer.Ordinal);

    /// <summary>
    /// A record's synthesized <c>Equals</c> compares its <em>fields</em>, never a computed
    /// property, so the census is over fields — the backing field of an <c>init</c> property
    /// included.
    /// </summary>
    private static IEnumerable<FieldInfo> Fields(Type type) =>
        type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly);

    /// <summary>
    /// Whether a value of this type is compared by the identity of an object behind it rather than
    /// by what it holds: an array, an <see cref="ImmutableArray{T}"/> (which is one), or a
    /// collection seen through an interface.
    /// </summary>
    private static bool ComparesByIdentity(Type type) =>
        type != typeof(string)
        && (type.IsArray
            || (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(ImmutableArray<>))
            || (type.IsInterface && typeof(IEnumerable).IsAssignableFrom(type)));

    /// <summary>Whether this type keeps the equality the compiler wrote for it.</summary>
    private static bool KeepsSynthesizedEquality(Type type) =>
        type.GetMethod("Equals", BindingFlags.Instance | BindingFlags.Public, null, [type], null)
            is not { } equals || equals.IsDefined(typeof(CompilerGeneratedAttribute), inherit: false);

    /// <summary>
    /// Every type a value of <paramref name="type"/> carries: itself, an array's element type, and
    /// every generic type argument — so <c>IReadOnlyList&lt;LimitationOutcome&gt;</c> yields
    /// <c>LimitationOutcome</c>. Walking field types alone reaches none of those, which is how a
    /// census of this missed four of its five answers (#97).
    /// </summary>
    private static IEnumerable<Type> Carried(Type type)
    {
        var bare = Nullable.GetUnderlyingType(type) ?? type;
        yield return bare;

        var inner = bare.IsArray && bare.GetElementType() is { } element
            ? [element]
            : bare.IsGenericType ? bare.GetGenericArguments() : [];
        foreach (var carried in inner.SelectMany(Carried))
        {
            yield return carried;
        }
    }

    [Fact]
    public void The_engine_assembly_references_the_kernel_and_never_the_randomness_package()
    {
        var referenced = typeof(EntryPoints).Assembly.GetReferencedAssemblies()
            .Select(a => a.Name ?? string.Empty)
            .Where(n => n.StartsWith("RulesKernel", StringComparison.Ordinal))
            .ToArray();

        Assert.Contains("RulesKernel", referenced);
        Assert.DoesNotContain("RulesKernel.Randomness", referenced);
    }

    [Fact]
    public void The_replay_identity_names_no_random_algorithm_and_pins_the_corpus()
    {
        Assert.True(Ruleset.Identity.IsDeterministicWithoutRandomness);
        Assert.Null(Ruleset.Identity.RandomAlgorithm);
        Assert.Equal(MapEntries.Baseline, Assert.Single(Ruleset.Identity.SourceBaselines));
    }

    [Fact]
    public void The_same_request_resolves_the_same_way_every_time()
    {
        var waiver = WaiverStatement.NoneHeld("§ 107.51", nameof(DeterminismTests));
        var request = new Requests.SpeedWithinLimitRequest { Groundspeed = Groundspeed.InMilesPerHour(99m), Waiver = waiver };

        var first = EntryPoints.SpeedWithinLimit.Resolve(request);
        for (var i = 0; i < 100; i++)
        {
            Assert.Equal(first, EntryPoints.SpeedWithinLimit.Resolve(request));
        }
    }

    /// <summary>
    /// No record in this engine both carries a collection compared by the identity of the object
    /// behind it and keeps the equality the compiler wrote — save four this repository has already
    /// taken up, none of which is a finding.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>This is the whole of what makes comparing a finding sound</b>
    /// (<see cref="Evaluation.EvaluatedRequirement.Equals(Evaluation.EvaluatedRequirement)"/>), and
    /// it establishes it without asking which findings are reachable: it ranges over every record
    /// the assembly holds, so a finding no fact set this repository knows how to build could ever
    /// produce is inside it anyway. Three attempts at answering the question by reachability were
    /// each wrong about what they had covered; this one has nothing to be wrong about.
    /// </para>
    /// <para>
    /// It fails by <em>name</em>, so a record that joins the list says which record and the reader
    /// does not have to rediscover it. Adding a name here is a decision, not a fix: it means the
    /// engine has one more place where two evaluations of one operation can differ over which
    /// object happened to carry an answer.
    /// </para>
    /// </remarks>
    [Fact]
    public void No_record_compares_a_collection_by_its_identity_but_the_four_already_taken_up()
    {
        var carryingOne = Records()
            .Where(type => Fields(type).Any(field => ComparesByIdentity(field.FieldType)))
            .ToArray();

        // The census is only worth anything if it is looking at something: these are the findings
        // #90 gave their own equality, and they must be among what was examined.
        Assert.Contains(typeof(OperatingLimitationsFinding), carryingOne);
        Assert.Contains(typeof(OverHumanBeingsFinding), carryingOne);
        Assert.Contains(typeof(PreflightActionsFinding), carryingOne);
        Assert.Contains(typeof(VisualObserverConditionsFinding), carryingOne);
        Assert.Contains(typeof(MultipleAircraftFinding), carryingOne);

        Assert.Equal(
            KnownToCompareACollectionByIdentity,
            carryingOne.Where(KeepsSynthesizedEquality).Select(type => type.Name).Order(StringComparer.Ordinal).ToArray());
    }

    /// <summary>
    /// Every field in this engine whose value is one of the map's own entry types, counted through
    /// element types as well as directly, is one of five this repository has looked at.
    /// </summary>
    /// <remarks>
    /// Comparing a finding reduces, level by level, to these — and <c>MapEntry</c> keeps the
    /// compiler's equality over an <see cref="ImmutableArray{T}"/>, so what keeps that sound is a
    /// condition stated on
    /// <see cref="Evaluation.EvaluatedRequirement.Equals(Evaluation.EvaluatedRequirement)"/> rather
    /// than anything here. This is the census that condition has to be true of, and it is measured
    /// rather than written down: a field that joins it turns this red by name, where prose about it
    /// went stale twice inside one change.
    /// </remarks>
    [Fact]
    public void Every_field_carrying_a_map_entry_is_one_of_the_five_the_soundness_condition_covers()
    {
        var mapSide = Records()
            .SelectMany(type => Fields(type).Select(field => (Type: type, Field: field)))
            .Where(held => Carried(held.Field.FieldType).Any(
                carried => carried == typeof(MapEntry) || carried == typeof(DerivedMapEntry) || carried == typeof(RegisteredEntry)))

            // The backing field of `Entry` is named `<Entry>k__BackingField`; the property is what
            // a reader recognises.
            .Select(held => $"{held.Type.Name}.{held.Field.Name.TrimStart('<').Split('>')[0]}")
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();

        Assert.Equal(KnownToCarryAMapEntry, mapSide);
    }
}
